name: Bug Report
description: Create a report to help us improve.
labels: "bug"

body:

  - type: markdown
    attributes:
      value: |
        ## Notice

        1. Please follow the [Code of Conduct](https://github.com/bytedance/bhook/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
        2. Please test using [the latest release](https://github.com/bytedance/bhook/releases) to make sure your issue has not already been fixed.
        3. Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/bytedance/bhook/issues?q=is%3Aissue+sort%3Acreated-desc+).

  - type: input
    attributes:
      label: bytehook Version
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Android OS Version
      placeholder: "10.0"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Android ABIs
      multiple: true
      options:
        - armeabi-v7a
        - arm64-v8a
    validations:
      required: true

  - type: input
    attributes:
      label: Device Manufacturers and Models
      placeholder: "Google Pixel 6 Pro, Samsung Galaxy S22 Ultra, ..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: |
        Please provide a clear and concise description of what the bug is.

        If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the code snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did.

        If you observe an error, please paste the **full** error message you got. In case of a native crash, please paste the **full** tombstone in the `/data/tombstones` directory. For non-rooted devices, refer to [bugreport](https://developer.android.com/studio/debug/bug-report).
    validations:
      required: true

  - type: markdown
    attributes:
      value: >
        Thanks for contributing! :tada:
